name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history
          lfs: true       # Enable Git LFS if needed

      - name: Set up Git credentials
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "yourusername"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://Jman666:$HF_TOKEN@huggingface.co/spaces/Jman666/News-Article-Extraction
          git push --force origin main
